server:
  port: 8088
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: grpc-server-user
  datasource:
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.26.21.6:6606/personnel_middle?characterEncoding=UTF-8
    username: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.lsl.entity
  configuration:
    mapUnderscoreToCamelCase: false
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
